name = "pathfinder-static"
compatibility_date = "2026-03-23"
main = "functions/generate.js"

[env.production]
vars = { NVIDIA_API_KEY = "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", SUPABASE_URL = "https://npqevqiwmsibqswtjjpc.supabase.co", SUPABASE_KEY = "sb_publishable_HR7eoJUtI058I2TQqdif1Q_wtwygTiR" }

[assets]
directory = "./public"